
version: "3.2"

networks:
  laravel:

volumes:
  db:

services:
  messagebroker:
    image: rabbitmq:3-management
    container_name: frete-facil-messagebroker
    hostname: rabbitmq
    ports:
      - "15672:15672"
    network_mode: "bridge"
    volumes:
     - ./storage/rabbitmq1:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=true

  webapp:
    build:
      context: .
      dockerfile: webapp.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: frete-facil-webapp
    ports:
      - "8000:80"
    volumes:
      - ./webapp/:/var/www/html
    depends_on:
      - messagebroker
      - db
    networks:
      - laravel

  consumer:
    build:
      context: .
      dockerfile: consumer.Dockerfile
    container_name: frete-facil-consumer
    ports:
      - "5000:5000"
    depends_on:
      - messagebroker
      - db
    networks:
      - laravel

  db:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=frete_facil_db
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '4406:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel