
version: "3.2"

volumes:
  db:

networks:
  fretefacilnet:

services:
  messagebroker:
    image: rabbitmq:3.10-alpine
    hostname: rabbitmq
    container_name: messagebroker
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
     - ./storage/rabbitmq1:/var/lib/rabbitmq
    environment:
     - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
     - RABBITMQ_DEFAULT_USER=guest
     - RABBITMQ_DEFAULT_PASS=guest
     - CLUSTERED=true
    networks:
      - fretefacilnet

  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: webapp.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8000:80"
    volumes:
      - ./webapp/:/var/www/html
      - ./webapp/ini:/usr/local/etc/php
      - ./spreadsheets:/var/www/html/storage/app/spreadsheets
    depends_on:
      - messagebroker
      - db
    networks:
      - fretefacilnet

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: consumer.Dockerfile
    depends_on:
      - messagebroker
      - db
    environment:
      - DB_USER=root
      - DB_PASSWORD=mauFJcuf5dhRMQrjj
      - DB_DATABASE=frete_facil_db
    networks:
      - fretefacilnet
    volumes:
      - ./spreadsheets:/code/spreadsheets

  db:
    image: mysql:5.7
    container_name: db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=frete_facil_db
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '4406:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fretefacilnet